"""version_simulation1

Revision ID: 1ea20facc463
Revises: 7721f91ea964
Create Date: 2024-05-20 11:15:21.048209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea20facc463'
down_revision = '7721f91ea964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
